function f = MAPE(x,kd,kl,buku,n,D,L)
    %%Input Transformation 
    gd = x(1);
    w  = x(2);
    gl = x(3);
    b  = x(4);
    D0 = D(1,buku);
    L0 = L(1,buku);
    %% MAPE Function Evaluation
    g=0;
    for t1=1:n
        t=t1-1;
        %DA = (gd-w)*kd/(-exp(-(gd-w)*t)*(D0*gd-gd*kd+kd*w)*gd/...
%               (D0*(gd-w))+exp(-(gd-w)*t)*(D0*gd-gd*kd+kd*w)*w/...
%               (D0*(gd-w))+gd);
        %LA = exp(-(b-gl)*t)/(gl*(-(D0*gd-gd*kd+kd*w)*gd*...
%               exp(-b*t-gd*t+gl*t+t*w)/(D0*(gd-w)*(-b-gd+gl+w))+...
%               (D0*gd-gd*kd+kd*w)*w*exp(-b*t-gd*t+gl*t+t*w)/(D0*(gd-w)*...
%               (-b-gd+gl+w))+gd*exp(-b*t+gl*t)/(-b+gl))/(kl*(gd-w))+...
%               (D0*L0*gd*gl+D0*b^2*kl+D0*b*gd*kl-2*D0*b*gl*kl-D0*b*kl*w-...
%               D0*gd*gl*kl+D0*gl^2*kl+D0*gl*kl*w+L0*b*gl*kd-L0*gl^2*kd)/...
%               (D0*L0*kl*(b^2+b*gd-2*b*gl-b*w-gd*gl+gl^2+gl*w)));
        DA = (D0*kd*(gd-w))/(D0*gd+(kd*(gd-w)-D0*gd)*exp((-gd+w)*t));
        P  = (D0*L0*kl*exp((gl-b)*t))*((gd^2+w^2)*(-gl+b)+(gl^2+b^2)*...
             (gd-w)+2*gd*w*gl*b*((1/gd)-(1/w)-(1/gl)+(1/b)));
        Q  = L0*gl*(gd-w)*(D0*gd+kd*(-gl+b))+(P/L0)*exp((-gl+b)*t) +...
             exp((gl-b)*t)*D0*L0*gd*w*(-gd+w+gl-b)+exp((-gd+w+gl-b)*t)*...
             L0*gl*(-gl+b)*(D0*gd+kd*(gd+w));
        LA = P/Q;
        s = (abs((D(t1,buku)- DA)/(D(t1,buku))))+...
            (abs((L(t1,buku)-LA)/L(t1,buku)));
        g = (g+s);
    end
        f = (1/2)*(100/n)*g;
 end